version : "3.8"

services:
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        networks:
            - inception
        env_file:
            - .env
        depends_on:
             - wordpress
        ports:
            - 443:443

    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        networks:
            - inception
        env_file:
            - .env
        # volumes:
        #     - /home/aaoutem-/data/mariadb:/var/lib/mysql
        expose:
            - 3306

    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        networks:
            - inception
        env_file:
            - .env
        depends_on:
            - mariadb
        # volumes:
        #     - /home/aaoutem-/data/wordpress:/var/www/wordpress
        expose:
            - 9000

networks:
    inception:
        driver: bridge
