version: "3.8"

services:
    mariadb:
        container_name: mariadb
        volumes:
            - mariadb:/var/lib/mysql
        build: ./requirements/mariadb
        networks:
            - inception
        env_file:
            - .env
        expose:
            - 3306
    wordpress:
        container_name: wordpress
        volumes:
            - wordpress:/var/www/wordpress
        build: ./requirements/wordpress
        networks:
            - inception
        env_file:
            - .env
        depends_on:
            - mariadb
        expose:
            - 9000
    nginx:
        container_name: nginx
        volumes:
            - wordpress:/var/www/wordpress:ro
        build: ./requirements/nginx
        networks:
            - inception
        env_file:
            - .env
        depends_on:
            - wordpress
        ports:
            - 443:443

networks:
    inception:
      driver: bridge

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/aaoutem-/data/wpvol
    mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/aaoutem-/data/mariadbvol
