version : "3.8"

services:
	nginx:
		build: ./requirements/nginx
	mariadb:
        build: ./requirements/mariadb
        envirement:
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}

	wordpress:
        build: ./requirements/wordpress
        depends_on:
            - mariadb
